name: Setup Build
description: Sets up the runner in preparation for CI builds
inputs:
  java-distribution:
    required: false
    description: Java distribution
    default: zulu
  java-version:
    required: false
    description: Java version
    default: 17
  setup-python:
    required: false
    description: If true, will install Python and any required dependencies
    default: false
  python-version:
    required: false
    description: Python version to install
    default: 3.10 # 3.12 removes distutils which may be required by some dependencies
  python-dependencies:
    required: false
    description: Optional Python dependencies to install
    default: ''
  setup-git:
    required: false
    description: If true, will set up authentication for Git
    default: false
  email:
    required: false
    description: E-mail used when configuring Git, will appear in any commits
  username:
    required: false
    description: User name used when configuring Git, will appear in any commits
  github-token:
    required: false
    description: Token used to authenticate with GitHub (requires cross-repo permissions)
  gpg-signing-key:
    required: false
    description: GPG signing key for signing Maven artifacts
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ inputs.gpg-signing-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Setup Git and GitHub CLI
      if: ${{ inputs.setup-git }}
      shell: bash
      run: |
        gh auth setup-git
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "${{ inputs.username }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Set up Matlab
      if: ${{ inputs.setup-matlab }}
      uses: matlab-actions/setup-matlab@v1
    - name: Set up Python ${{ inputs.python-version }}
      if: ${{ inputs.setup-python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip
    - name: Set up Python dependencies
      if: ${{ inputs.setup-python && inputs.python-dependencies != '' }}
      shell: bash
      run: python -m pip install ${{ inputs.python-dependencies }}
