name: Setup Build
description: Sets up the runner in preparation for CI builds
inputs:
  java-distribution:
    type: choice
    required: true
    description: Java distribution
    options:
      - 'zulu'
      - 'temurin'
      - 'oracle'
    default: 'zulu'
  java-version:
    type: choice
    required: true
    description: Java version
    options:
      - '17'
      - '18'
      - '19'
      - '20'
      - '21'
      - '22'
    default: '17'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
