name: Setup Build
description: Sets up the runner in preparation for builds
inputs:
  java-distribution:
    type: choice
    required: true
    description: Java distribution
    options:
      - 'zulu'
      - 'temurin'
      - 'oracle'
    default: 'zulu'
  java-version:
    type: choice
    required: true
    description: Java version
    options:
      - '17'
      - '18'
      - '19'
      - '20'
      - '21'
      - '22'
    default: '17'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Setup Git and GitHub CLI
      shell: bash
      run: |
        gh auth setup-git
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
