name: Get Release
description: 
inputs:
  version:
    description: 'Desired version, or "latest" to get the most recent release'
    default: 'latest'
runs:
  using: "composite"
  steps:
    - name: Download release
      shell: bash
      run: |
        if [ "${{ inputs.version || 'latest' }}" = "latest" ]; then
          MOEAFRAMEWORK_VERSION=$(gh release view --repo MOEAFramework/MOEAFramework --json tagName --jq ".tagName" | grep -oEi '[0-9]+\.[0-9]+(\.[0-9]+)?')
          echo "Latest MOEAFramework Release: ${MOEAFRAMEWORK_VERSION}"
        else
          MOEAFRAMEWORK_VERSION="${{ inputs.version }}"
        fi
          
        wget https://github.com/MOEAFramework/MOEAFramework/releases/download/v${VERSION}/MOEAFramework-${MOEAFRAMEWORK_VERSION}.tar.gz
        tar -xzf MOEAFramework-${MOEAFRAMEWORK_VERSION}.tar.gz

        MOEAFRAMEWORK_ROOT=$(realpath -s MOEAFramework-${MOEAFRAMEWORK_VERSION})

        echo "MOEAFRAMEWORK_VERSION=${MOEAFRAMEWORK_VERSION}" >> $GITHUB_ENV
        echo "MOEAFRAMEWORK_ROOT=${MOEAFRAMEWORK_ROOT}" >> $GITHUB_ENV
