name: Run Ant
description: Runs an Ant target
inputs:
  directory:
    description: Directory to run Ant
    required: false
    default: '.'
  target:
    description: The Ant target
    required: false
    default: ''
  file:
    description: The Ant file, relative to the directory
    required: false
    default: build.xml
  warning:
    description: If set, will display this warning message instead of failing
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Run Ant target
      shell: bash
      run: |
        pushd ${{ inputs.directory }}

        ant_result=0
        ant -f ${{ inputs.file }} ${{ inputs.target }} || ant_result=$?
          
        if [ "$ant_result" -ne "0" ]; then
          if [ -n "${{ inputs.warning }}" ]; then
            echo "::warning title=Warning::${{ inputs.warning }}"
          else
            exit $ant_result
          fi
        fi
        
