name: Publish Maven
description: Build and stage Maven artifacts
inputs:
  directory:
    description: Root directory for the Maven project
    required: false
    default: '.'
  skip-tests:
    description: Skip running Maven tests before deploy
    required: false
    default: false
  ossrh-username:
    description: Username for authenticating with OSSRH
    required: true
  ossrh-password:
    description: Password for authenticating with OSSRH
    required: true
  gpg-passphrase:
    description: Passphrase for accessing the GPG signing key
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and stage Maven artifacts
      shell: bash
      run: |
        pushd ${{ inputs.directory }}
        mvn --batch-mode deploy -Dmaven.test.skip=${{ inputs.skip-tests }}
      env:
        MAVEN_USERNAME: ${{ inputs.ossrh-username }}
        MAVEN_PASSWORD: ${{ inputs.ossrh-password }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
