name: Setup Release
description: Sets up the runner in preparation for release builds
inputs:
  email:
    type: string
    required: true
    description: E-mail used when configuring Git, will appear in any commits
  username:
    type: string
    required: true
    description: User name used when configuring Git, will appear in any commits
  github-pat:
    type: string
    required: true
    description: PAT used to authenticate with GitHub when working across repos
  gpg-signing-key:
    type: string
    required: true
    description: GPG signing key for signing Maven artifacts
  java-distribution:
    type: choice
    required: true
    description: Java distribution
    options:
      - 'zulu'
      - 'temurin'
      - 'oracle'
    default: 'zulu'
  java-version:
    type: choice
    required: true
    description: Java version
    options:
      - '17'
      - '18'
      - '19'
      - '20'
      - '21'
      - '22'
    default: '17'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ inputs.gpg-signing-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Setup Git and GitHub CLI
      shell: bash
      run: |
        gh auth setup-git
        git config --global user.email "${{ inputs.email }}"
        git config --global user.name "${{ inputs.username }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-pat }}
