name: Publish GitHub Release
description: Stage a GitHub release including any Maven or Ant release artifacts
inputs:
  release-notes-file:
    required: false
    description: The file containing release notes (note this must follow our release note format)
  extra-files:
    required: false
    description: Extra files to include in the release
  github-token:
    required: true
    description: Token used to authenticate with GitHub
runs:
  using: "composite"
  steps:
    - name: Stage GitHub release
      shell: bash
      run: |
        if [ -n "${{ inputs.release-notes-file }}" ]; then
          cat "${{ inputs.release-notes-file }}" | awk '/## Version ${BUILD_VERSION}/{flag=1; next} /##/{flag=0} flag' > generatedReleaseNotes.md
          [ "$(wc -l < generatedReleaseNotes.md)" -gt 0 ] || (>&2 echo "Unable to read release notes from ${{ inputs.release-notes-file }}"; exit -1)
        fi
        
        gh release create "v${BUILD_VERSION}" --draft --title "Version ${BUILD_VERSION}" \
            $([ -f "generatedReleaseNotes.md" ] && echo "--notes-file generatedReleaseNotes.md" || echo "") \
            $([ -n "${{ inputs.extra-files }}" ] && echo "${{ inputs.extra-files }}" || echo "") \
            $([ -f "dist/MOEAFramework-${BUILD_VERSION}.tar.gz" ] && echo "dist/MOEAFramework-${BUILD_VERSION}.tar.gz" || echo "") \
            $([ -f "dist/MOEAFramework-${BUILD_VERSION}-Demo.jar" ] && echo "dist/MOEAFramework-${BUILD_VERSION}-Demo.jar" || echo "") \
            $([ -f "dist/MOEAFramework-${BUILD_VERSION}-Source.tar.gz" ] && echo "dist/MOEAFramework-${BUILD_VERSION}-Source.tar.gz" || echo "") \
            $([ -f "target/${BUILD_ARTIFACT}.jar" ] && echo "target/${BUILD_ARTIFACT}.jar" || echo "") \
            $([ -f "target/${BUILD_ARTIFACT}-jar-with-dependencies.jar" ] && echo "target/${BUILD_ARTIFACT}-jar-with-dependencies.jar" || echo "")
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
