name: Get Project Build Info
description: Populates several environment variables with the project name, version, etc.
runs:
  using: "composite"
  steps:
    - name: Get project info
      shell: bash
      run: |
        if [ -f META-INF/build.properties ]; then
            BUILD_NAME=$(sed -En 's=.*shortname[ ]*\=[ ]*(.*)[ ]*=\1=p' META-INF/build.properties | head -n 1 | tr '[:upper:]' '[:lower:]')
            BUILD_VERSION=$(sed -En 's=.*version[ ]*\=[ ]*(.*)[ ]*=\1=p' META-INF/build.properties | head -n 1)
        elif [ -f pom.xml ]; then
            BUILD_NAME=$(sed -En 's=.*<artifactId>(.*)</artifactId>.*=\1=p' pom.xml | head -n 1)
            BUILD_VERSION=$(sed -En 's=.*<version>(.*)</version>.*=\1=p' pom.xml | head -n 1)
        fi
          
        [ -n "${BUILD_NAME}" ] || (>&2 echo "Failed to detect BUILD_NAME"; exit -1)
        [ -n "${BUILD_VERSION}" ] || (>&2 echo "Failed to detect BUILD_VERSION"; exit -1)
        BUILD_YEAR=$(date +%Y)
        BUILD_ARTIFACT="${BUILD_NAME}-${BUILD_VERSION}"
        
        echo "BUILD_NAME=${BUILD_NAME}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
        echo "BUILD_YEAR=${BUILD_YEAR}" >> $GITHUB_ENV
        echo "BUILD_ARTIFACT=${BUILD_ARTIFACT}" >> $GITHUB_ENV

        if echo "${BUILD_VERSION}" | grep -i ".*-SNAPSHOT" > /dev/null; then
          echo "IS_SNAPSHOT=true" >> $GITHUB_ENV
        fi
