name: Reusable Maven CI

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        description: The runner OS
        default: 'ubuntu-latest'
      java-distribution:
        type: string
        required: false
        description: Java distribution
        default: 'zulu'
      minimum-java-version:
        type: string
        required: false
        description: Minimum Java version
        default: '17'

jobs:
  test:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '17', '18', '19', '20', '21', '22' ]
    if: ${{ matrix.java >= inputs.minimum-java-version }}
    steps:
      - name: Setup build
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: ${{ matrix.java }}
          java-distribution: ${{ inputs.java-distribution }}
      - name: Run tests
        run: mvn test
